"""Unified genre registry — the SINGLE source of truth for genre/style info,
used everywhere it's needed:

- `tags`  → ACE-Step generation tag bundle (the Generate/Song/Restyle preset chips)
- `bpm` / `key` → SUGGESTED tempo + key (suggestions, never force-applied)
- `scale` → modal scale the symbolic riff/solo generator realises against
- `riff`  → LLM prompt feel for a rhythm riff
- `solo`  → LLM prompt feel for a lead solo
- `lead`  → riff renders single notes (shred) instead of power chords (optional)
- `reg`   → register offset in semitones for the riff/solo (optional)
- `parent`→ id of the genre this entry is a BAND/artist style under (optional). Band
            entries stay in the same flat registry (so riff/solo lookup by id is
            unchanged) but the UI nests them under their parent genre instead of
            cluttering the top-level genre list. Top-level genres have no `parent`.

Exposed to the frontend via /api/config ("genres") and consumed by guitar.py
for symbolic riff/solo generation. Add a genre here once → it appears in the
generation chips AND the Guitar riff/solo genre pickers.

NOTE on `solo` wording: the symbolic generator only places notes on a 16th-note
grid (it can't render bends/vibrato/pinch-harmonics/wah). So the solo prompts
lead with what the grid CAN express — note density/speed, how high to climb,
melodic contour (runs / leaps / pedal points / repeated motifs / sequences),
which characteristic scale tones to lean on, and phrasing (rests vs continuous).
"""

GENRES = [
    {"id": "power", "label": "Power", "bpm": 175, "key": "E minor", "scale": "minor",
     "tags": "power metal, galloping double-bass drums, fast palm-muted distorted guitars, twin lead guitar harmonies, soaring clean operatic male vocals, orchestral keyboards, triumphant, epic, fast tempo",
     "riff": "fast galloping, melodic and uplifting; mostly root chugs with soaring runs up to 5/8 and harmonised-sounding leaps",
     "solo": "fast triumphant legato runs that climb high (degrees to 12-15) and resolve onto held, singable peaks; mostly continuous with short breaths between phrases; melodic upward leaps, major-leaning"},
    {"id": "battle_beast", "label": "Battle Beast", "parent": "power", "bpm": 155, "key": "E minor", "scale": "minor",
     "tags": "modern power metal, 80s hard rock influence, anthemic fist-pumping choruses, driving palm-muted distorted guitars, galloping double-bass drums, 80s synthesizer and keytar layers, powerful high belting female vocals, symphonic touches, catchy, energetic, Battle Beast style",
     "riff": "driving mid-fast power-metal riffing with 80s hard-rock swagger; galloping palm-muted root chugs with melodic moves up the minor scale, anthemic and punchy",
     "solo": "melodic 80s-flavoured lead — fast singable runs resolving onto held high notes around a hooky repeated motif; energetic with balanced rests"},
    {"id": "beast_in_black", "label": "Beast in Black", "parent": "power", "bpm": 165, "key": "E minor", "scale": "minor",
     "tags": "power metal fused with 80s synthwave, bright retro synthesizers, tight palm-muted galloping distorted guitars, double-bass drums, soaring high melodic male vocals, hooky danceable choruses, 80s Italo-disco influence, catchy, energetic, Beast in Black style",
     "riff": "tight palm-muted galloping chugs locked to a danceable beat under bright synthwave; catchy, melodic minor, driving",
     "solo": "hooky melodic shred lead — fast scalar runs and a catchy repeated motif climbing to held high notes; energetic 80s synthwave phrasing"},
    {"id": "sabaton", "label": "Sabaton", "parent": "power", "bpm": 140, "key": "E minor", "scale": "minor",
     "tags": "power metal, military and war history themes, mid-tempo marching rhythms, heavy palm-muted distorted guitars, bombastic orchestral keyboards, anthemic singalong gang choruses, gruff powerful male vocals, triumphant and heroic, Sabaton style",
     "riff": "mid-tempo marching power-metal chug, heavy palm-muted root chords locked to a martial beat with simple melodic moves, anthemic and punchy",
     "solo": "melodic anthemic lead, singable mid-fast runs resolving onto held high notes over a marching feel, moderate density with clear rests"},
    {"id": "helloween", "label": "Helloween", "parent": "power", "bpm": 172, "key": "E minor", "scale": "minor",
     "tags": "melodic speed power metal, fast galloping double-bass drums, bright major-leaning melodies, twin lead guitar harmonies, soaring clean high male vocals, catchy uplifting choruses, classic pumpkin-era power metal, Helloween style",
     "riff": "fast galloping speed-metal riff, bright and melodic, mostly root gallops with happy major-leaning runs up the scale and harmonised leaps",
     "solo": "fast happy melodic lead, twin-harmony runs climbing high to singable peaks around a catchy motif, energetic and mostly continuous"},
    {"id": "hammerfall", "label": "HammerFall", "parent": "power", "bpm": 150, "key": "E minor", "scale": "minor",
     "tags": "classic heavy power metal, traditional steel and templar themes, mid-fast crunchy distorted guitars, twin guitar harmonies, anthemic fist-pumping choruses, strong melodic male vocals, triumphant, HammerFall style",
     "riff": "classic mid-fast heavy/power riffing, crunchy power chords with melodic moves and the occasional gallop, traditional and anthemic",
     "solo": "traditional melodic metal lead, singable runs and twin-harmony lines climbing the scale to held notes, balanced rests and heroic"},
    {"id": "blind_guardian", "label": "Blind Guardian", "parent": "power", "bpm": 165, "key": "E minor", "scale": "minor",
     "tags": "epic speed power metal, densely layered vocal harmonies and bard choirs, galloping double-bass drums, intricate twin guitars, fantasy and Tolkien themes, raspy powerful male vocals, orchestral grandeur, Blind Guardian style",
     "riff": "intricate galloping speed-metal riff, busy and melodic with running 16th gallops and harmonised moves up the scale, epic and dense",
     "solo": "busy epic lead, fast intricate runs and harmonised motifs climbing high with few rests, dramatic and layered"},
    {"id": "dragonforce", "label": "DragonForce", "parent": "power", "bpm": 200, "key": "E minor", "scale": "minor",
     "tags": "extreme power metal, blistering ultra-fast double-bass drums, virtuoso video-game shred lead guitars, soaring high clean vocals, fantasy themes, relentless speed, uplifting major-leaning melodies, DragonForce style",
     "riff": "relentless ultra-fast power-metal gallop, continuous high-speed palm-muted chugs with rapid melodic runs, frantic and bright",
     "solo": "blistering video-game shred, extremely fast continuous 16th runs, tapping sequences and arpeggio flurries climbing to the very top of the range, almost no rests"},
    {"id": "powerwolf", "label": "Powerwolf", "parent": "power", "bpm": 150, "key": "E minor", "scale": "minor",
     "tags": "power metal with cathedral church organ, gothic religious and werewolf horror themes, gang-chant Latin choirs, theatrical anthemic choruses, heavy palm-muted guitars, operatic powerful male vocals, dramatic, Powerwolf style",
     "riff": "mid-fast anthemic power riff under big church organ, heavy palm-muted chugs with melodic minor moves, theatrical and driving",
     "solo": "theatrical melodic lead, singable runs over organ climbing to held dramatic high notes around a chant-like motif, moderate rests"},
    {"id": "manowar", "label": "Manowar", "parent": "power", "bpm": 130, "key": "E minor", "scale": "minor",
     "tags": "epic true heavy power metal, bombastic warrior and steel themes, mid-tempo pounding drums, thick distorted guitars, prominent bass, soaring powerful operatic male vocals, anthemic battle hymns, Manowar style",
     "riff": "slow-to-mid epic heavy riff, thick pounding power chords, simple and mighty with the occasional melodic climb, bombastic",
     "solo": "epic soaring lead, long held high notes answered by melodic runs, dramatic and spacious with bold rests climbing to a triumphant peak"},
    {"id": "stratovarius", "label": "Stratovarius", "parent": "power", "bpm": 170, "key": "A minor", "scale": "harmonic_minor",
     "tags": "neoclassical melodic power metal, fast double-bass drums, duelling keyboard and guitar leads, soaring clean male vocals, uplifting bright melodies, baroque classical touches, Stratovarius style",
     "riff": "fast melodic neoclassical power riff, galloping chugs with harmonic-minor runs and keyboard-doubled moves, bright and uplifting",
     "solo": "fast neoclassical lead, flashy harmonic-minor runs and arpeggio sweeps trading with keyboards, climbing high to singable peaks leaning on the raised 7th"},
    {"id": "rhapsody", "label": "Rhapsody of Fire", "parent": "power", "bpm": 165, "key": "E minor", "scale": "harmonic_minor",
     "tags": "symphonic film-score power metal, full orchestra and epic choir, neoclassical shred guitars, operatic powerful male vocals, dragons and fantasy concept, bombastic cinematic grandeur, Rhapsody of Fire style",
     "riff": "grand neoclassical power riff over full orchestra, galloping chugs with harmonic-minor runs and harmonised leaps, cinematic and bombastic",
     "solo": "cinematic neoclassical shred, fast sweep arpeggios and harmonic-minor runs soaring over the orchestra to held epic peaks, dramatic"},
    {"id": "avantasia", "label": "Avantasia", "parent": "power", "bpm": 140, "key": "E minor", "scale": "minor",
     "tags": "symphonic power metal rock opera, theatrical multi-vocalist arrangements, anthemic melodic choruses, lush keyboards and orchestration, soaring and gritty trading male vocals, grand cinematic feel, Avantasia style",
     "riff": "mid-tempo melodic power riff supporting a rock-opera arrangement, anthemic power chords with melodic moves, grand and catchy",
     "solo": "melodic theatrical lead, soaring singable phrases mixing held notes and medium runs, expressive with dramatic rests climbing to a hook"},
    {"id": "gloryhammer", "label": "Gloryhammer", "parent": "power", "bpm": 172, "key": "E minor", "scale": "minor",
     "tags": "epic fantasy power metal, heroic sci-fi fantasy narrative, bright orchestral keyboards, fast galloping double-bass drums, soaring clean male vocals, anthemic singalong choruses, bombastic and tongue-in-cheek, Gloryhammer style",
     "riff": "fast galloping fantasy power riff, bright melodic chugs with runs up the scale under big keys, heroic and anthemic",
     "solo": "heroic melodic lead, fast singable runs climbing high to held triumphant peaks around a catchy motif, energetic"},
    {"id": "edguy", "label": "Edguy", "parent": "power", "bpm": 160, "key": "E minor", "scale": "minor",
     "tags": "melodic power metal, catchy hook-driven choruses, fun and energetic, mid-fast crunchy guitars, bright keyboards, charismatic clean male vocals, anthemic, Edguy style",
     "riff": "mid-fast catchy power riff, crunchy melodic power chords with hooky moves up the scale, fun and driving",
     "solo": "catchy melodic lead, singable mid-fast runs around a hooky repeated motif resolving to held notes, balanced rests"},
    {"id": "freedom_call", "label": "Freedom Call", "parent": "power", "bpm": 178, "key": "E minor", "scale": "minor",
     "tags": "happy melodic power metal, uplifting major-leaning melodies, fast double-bass drums, bright keyboards, anthemic gang-shout choruses, soaring clean male vocals, joyful and triumphant, Freedom Call style",
     "riff": "fast bright happy power riff, galloping chugs with major-leaning runs up the scale, joyful and anthemic",
     "solo": "happy uplifting lead, fast major-leaning runs climbing to singable high peaks around a gang-chant motif, energetic with few rests"},
    {"id": "kamelot", "label": "Kamelot", "parent": "power", "bpm": 140, "key": "E minor", "scale": "minor",
     "tags": "dark cinematic power metal, moody atmospheric orchestration, melodic mid-tempo guitars, smooth powerful baritone male vocals, progressive touches, elegant and dramatic, Kamelot style",
     "riff": "moody mid-tempo power riff, melodic palm-muted chords with dark atmospheric moves, elegant and cinematic",
     "solo": "dark melodic lead, expressive medium runs and held emotive high notes over orchestration, spacious with dramatic rests"},
    {"id": "sonata_arctica", "label": "Sonata Arctica", "parent": "power", "bpm": 170, "key": "E minor", "scale": "minor",
     "tags": "melodic neoclassical power metal, fast double-bass drums, emotional bright melodies, prominent keyboards, soaring expressive clean male vocals, winter and wolf themes, catchy, Sonata Arctica style",
     "riff": "fast melodic power riff, galloping chugs with emotional melodic runs and keyboard doubling, bright and catchy",
     "solo": "emotional fast lead, flashy melodic runs and keyboard-trading lines climbing high to expressive peaks, energetic with feeling"},
    {"id": "angra", "label": "Angra", "parent": "power", "bpm": 160, "key": "E minor", "scale": "harmonic_minor",
     "tags": "Brazilian progressive power metal, technical neoclassical guitars, Latin and folk rhythmic touches, soaring high clean male vocals, intricate arrangements, bright and virtuosic, Angra style",
     "riff": "technical progressive power riff, intricate galloping chugs with harmonic-minor runs and syncopated Latin-tinged moves, virtuosic",
     "solo": "virtuosic neoclassical lead, fast intricate harmonic-minor runs and sweep arpeggios with progressive phrasing climbing high, busy"},
    {"id": "imperial_age", "label": "Imperial Age", "parent": "symphonic", "bpm": 150, "key": "D minor", "scale": "minor",
     "tags": "symphonic metal, full operatic choir of multiple vocalists, lush cinematic orchestra, heavy distorted guitars, soaring soprano and powerful male leads, bombastic and grand, Imperial Age style",
     "riff": "grand symphonic power-chord riff supporting full orchestra and choir, mid-fast and dramatic with melodic minor moves",
     "solo": "soaring cinematic lead, long sustained high notes and expressive runs following the orchestra, dramatic rests climbing grandly"},
    {"id": "therion", "label": "Therion", "parent": "symphonic", "bpm": 140, "key": "D minor", "scale": "minor",
     "tags": "operatic symphonic metal, classical choirs and orchestration, occult and mythological themes, heavy guitars under grand opera vocals, dramatic and ceremonial, Therion style",
     "riff": "ceremonial symphonic riff, heavy mid-tempo power chords under classical choir and orchestra, dramatic and grand",
     "solo": "operatic melodic lead, stately held high notes and classical-flavoured runs over the choir, spacious and dramatic"},
    {"id": "alestorm", "label": "Alestorm", "parent": "pirate", "bpm": 160, "key": "E minor", "scale": "minor",
     "tags": "pirate metal, raucous sea-shanty gang vocals, accordion and keytar leads, fast folk-metal guitars, drinking and high-seas themes, rowdy and fun, festive singalong choruses, Alestorm style",
     "riff": "rowdy fast folk/pirate riff, bouncy galloping chugs with shanty-like melodic runs and accordion doubling, festive",
     "solo": "jaunty pirate lead, bouncy fast folk runs and a singalong shanty motif traded with accordion or keytar, lively with a lilt"},
    {"id": "nightwish", "label": "Nightwish", "parent": "symphonic", "bpm": 135, "key": "D minor", "scale": "minor",
     "tags": "symphonic metal, soaring operatic and versatile female lead vocals, vast cinematic orchestra and choir, heavy distorted guitars, folk and Celtic touches, fantasy and nature themes, epic soft-to-loud dynamics, Nightwish style",
     "riff": "grand symphonic power-chord riff under a full orchestra, mid-tempo and melodic with dramatic minor moves and soft-to-loud dynamics",
     "solo": "soaring cinematic lead, long sustained high notes and expressive melodic runs following the orchestra, dramatic rests and grand climbs"},
    {"id": "epica", "label": "Epica", "parent": "symphonic", "bpm": 145, "key": "E minor", "scale": "minor",
     "tags": "symphonic metal, operatic soprano female vocals contrasted with male death growls, full orchestra and grand choir, heavy djent-leaning palm-muted guitars, philosophical and spiritual themes, bombastic and intricate, Epica style",
     "riff": "heavy djent-leaning symphonic riff, tight low palm-muted chugs syncopated under full orchestra and choir, dramatic and modern",
     "solo": "dramatic neoclassical lead, fast melodic runs and held high notes weaving through the orchestra, intricate with dynamic rests"},
    {"id": "visions_of_atlantis", "label": "Visions of Atlantis", "parent": "symphonic", "bpm": 140, "key": "E minor", "scale": "minor",
     "tags": "symphonic metal, dual operatic female and powerful male vocals trading lines, lush cinematic orchestra, ocean nautical and pirate themes, melodic heavy guitars, epic and adventurous, Visions of Atlantis style",
     "riff": "epic mid-tempo symphonic riff, melodic power chords under sweeping orchestra, adventurous and grand with minor moves",
     "solo": "adventurous melodic lead, soaring singable phrases and held high notes over orchestral swells, expressive with dramatic rests"},
    {"id": "within_temptation", "label": "Within Temptation", "parent": "symphonic", "bpm": 130, "key": "E minor", "scale": "minor",
     "tags": "symphonic gothic metal, emotive powerful female lead vocals, atmospheric cinematic orchestration, melodic mid-tempo guitars, dramatic anthemic choruses, dark and moving, Within Temptation style",
     "riff": "atmospheric mid-tempo symphonic riff, melodic palm-muted power chords under cinematic strings, dark and emotive",
     "solo": "emotive melodic lead, expressive medium runs and long held high notes over orchestration, spacious and dramatic"},
    {"id": "delain", "label": "Delain", "parent": "symphonic", "bpm": 140, "key": "E minor", "scale": "minor",
     "tags": "symphonic metal, catchy melodic female lead vocals, lush keyboards and orchestration, polished modern heavy guitars, anthemic choruses, bright and emotional, Delain style",
     "riff": "polished mid-fast symphonic riff, melodic power chords under bright keys, catchy and driving",
     "solo": "catchy melodic lead, singable mid-fast runs and held high notes over keyboards, bright with balanced rests"},
    {"id": "xandria", "label": "Xandria", "parent": "symphonic", "bpm": 145, "key": "D minor", "scale": "minor",
     "tags": "symphonic metal, soaring classically-trained operatic soprano vocals, bombastic full orchestra and choir, heavy distorted guitars, grand cinematic fantasy themes, majestic, Xandria style",
     "riff": "bombastic symphonic power-chord riff under grand orchestra and choir, mid-fast and majestic with dramatic minor moves",
     "solo": "majestic operatic lead, stately held high notes and flowing melodic runs over the orchestra, grand and dramatic"},
    {"id": "leaves_eyes", "label": "Leaves' Eyes", "parent": "symphonic", "bpm": 140, "key": "E minor", "scale": "minor",
     "tags": "symphonic Viking metal, operatic female vocals contrasted with harsh male growls, sweeping orchestra and choir, Norse and historical seafaring themes, heavy melodic guitars, epic, Leaves Eyes style",
     "riff": "epic mid-tempo Viking symphonic riff, melodic power chords under sweeping orchestra, grand and battle-ready",
     "solo": "epic melodic lead, soaring held notes and folk-tinged runs over orchestral swells, dramatic with bold rests"},
    {"id": "ad_infinitum", "label": "Ad Infinitum", "parent": "symphonic", "bpm": 145, "key": "E minor", "scale": "minor",
     "tags": "modern symphonic metal, powerful versatile female vocals with occasional harsh growls, cinematic orchestration, polished heavy guitars, catchy anthemic choruses, energetic, Ad Infinitum style",
     "riff": "modern mid-fast symphonic riff, tight palm-muted power chords under cinematic strings, catchy and punchy",
     "solo": "energetic melodic lead, fast singable runs and held high notes over orchestration, modern with balanced rests"},
    {"id": "beyond_the_black", "label": "Beyond the Black", "parent": "symphonic", "bpm": 140, "key": "E minor", "scale": "minor",
     "tags": "modern melodic symphonic metal, strong clear female lead vocals, polished anthemic production, cinematic keyboards, heavy melodic guitars, catchy stadium choruses, Beyond the Black style",
     "riff": "polished mid-fast melodic riff, bright palm-muted power chords under cinematic keys, anthemic and driving",
     "solo": "anthemic melodic lead, singable mid-fast runs climbing to held high notes, polished with clear rests"},
    {"id": "tarja", "label": "Tarja", "parent": "symphonic", "bpm": 135, "key": "D minor", "scale": "minor",
     "tags": "symphonic metal, dramatic classically-trained operatic soprano lead vocals, dark cinematic orchestration, heavy distorted guitars, grand and theatrical with gothic touches, Tarja Turunen style",
     "riff": "dramatic mid-tempo symphonic riff, heavy melodic power chords under dark orchestra, theatrical and grand",
     "solo": "dramatic operatic lead, long sustained soprano-like held notes and expressive runs over the orchestra, spacious and intense"},
    {"id": "dominum", "label": "Dominum", "parent": "power", "bpm": 150, "key": "E minor", "scale": "minor",
     "tags": "modern melodic metal, theatrical horror and undead post-apocalyptic themes, anthemic catchy singalong choruses, heavy palm-muted guitars, bright keyboards, powerful clean male vocals, energetic and tongue-in-cheek, Dominum style",
     "riff": "driving mid-fast melodic metal riff, heavy palm-muted chugs with hooky melodic moves, theatrical and anthemic",
     "solo": "catchy melodic lead, singable fast runs climbing to held high notes around a hooky motif, energetic"},
    {"id": "amaranthe", "label": "Amaranthe", "parent": "power", "bpm": 150, "key": "E minor", "scale": "minor",
     "tags": "modern melodic metal, three trading vocalists with clean female cleans and harsh male growls, electronic synth hooks and pop sensibility, tight djent-leaning palm-muted guitars, energetic danceable choruses, Amaranthe style",
     "riff": "tight modern palm-muted riff, low syncopated chugs locked to electronic beats, punchy and danceable",
     "solo": "short flashy modern lead, fast melodic runs over synths resolving to a hook, energetic and concise"},
    {"id": "lacuna_coil", "label": "Lacuna Coil", "parent": "gothic", "bpm": 130, "key": "E minor", "scale": "minor",
     "tags": "gothic metal, dual female and male vocals trading melodic and harsh lines, dark atmospheric mid-tempo guitars, brooding melodic hooks, moody and modern, Lacuna Coil style",
     "riff": "brooding mid-tempo gothic riff, heavy melodic palm-muted chords with dark atmospheric moves, moody and groovy",
     "solo": "moody melodic lead, expressive medium runs and held dark notes, spacious with dramatic rests"},
    {"id": "sirenia", "label": "Sirenia", "parent": "gothic", "bpm": 135, "key": "D minor", "scale": "minor",
     "tags": "gothic symphonic metal, operatic female vocals and male death growls, lush orchestration and choir, dark melancholic atmosphere, heavy melodic guitars, dramatic, Sirenia style",
     "riff": "dark symphonic gothic riff, heavy melodic power chords under mournful orchestra, dramatic and brooding",
     "solo": "melancholic melodic lead, soaring held high notes and expressive runs over the orchestra, dramatic and dark"},
    {"id": "neoclassical", "label": "Neoclassical", "bpm": 168, "key": "A minor", "scale": "harmonic_minor",
     "lead": True, "reg": 24,
     "tags": "neoclassical metal, virtuoso shred lead guitar, fast sweep-picked arpeggios and harmonic-minor scalar runs, baroque classical influence, galloping double-bass drums, harpsichord and orchestral keyboards, soaring operatic male vocals, dramatic, Yngwie Malmsteen style",
     "riff": "virtuosic neoclassical shred (Yngwie/Becker): FAST continuous 16th SINGLE-NOTE harmonic-minor runs (raised-7th leading tone), pedal-point lines and diminished/sequence flurries; busy, few rests, ranging high (degrees to 12-15); a lead line, NOT power chords",
     "solo": "relentless 16th harmonic-minor runs, arpeggio-leap sweeps and pedal-point sequences climbing to the very top of the range (degrees 12-15); almost no rests; lean on the raised-7th leading tone and the b6 — pure Yngwie virtuosity"},
    {"id": "symphonic", "label": "Symphonic", "bpm": 150, "key": "D minor", "scale": "minor",
     "tags": "symphonic metal, lush orchestral strings, epic choir, heavily distorted guitars, double-bass drums, soaring operatic female vocals, cinematic, dramatic, grand",
     "riff": "grand, mid-fast power chords supporting an orchestra; melodic, dramatic, with melodic moves up the minor scale",
     "solo": "soaring cinematic melody — long sustained high notes answered by expressive medium runs; moderate density with dramatic rests; climbs then resolves, following the orchestra"},
    {"id": "folk_metal", "label": "Folk", "bpm": 160, "key": "E minor", "scale": "dorian",
     "tags": "folk metal, distorted electric guitars, double-bass drums, folk melody, violin, flute, accordion, anthemic gang vocals, festive, energetic",
     "riff": "lively, modal and melodic (dorian); bouncy mid-fast riff with folky melodic runs, major-ish",
     "solo": "jaunty dorian dance melody — bouncy mid-fast runs and ornaments built on a repeating singable motif; lean on the raised 6th; small rests for the lilt"},
    {"id": "heavy", "label": "Heavy", "bpm": 140, "key": "E minor", "scale": "minor",
     "tags": "heavy metal, crunchy distorted electric guitars, twin guitar harmonies, driving drums, powerful melodic male vocals, classic, high energy",
     "riff": "classic mid-tempo heavy-metal riffing; crunchy power chords with melodic moves and the occasional gallop",
     "solo": "classic melodic metal lead — singable medium-fast phrases mixing runs and held notes; balanced rests; climbs the scale and resolves to the root"},
    {"id": "nwobhm", "label": "NWOBHM", "bpm": 160, "key": "E minor", "scale": "minor",
     "tags": "NWOBHM, galloping twin-guitar harmonies, melodic distorted guitars, driving drums, soaring melodic male vocals, Iron Maiden style, heroic, energetic",
     "riff": "galloping, melodic and harmonised (Maiden-style); running 8th+16th gallops with melodic moves up the scale, heroic",
     "solo": "Maiden-style heroic lead — galloping melodic runs and a repeated harmonised-sounding motif climbing the scale; energetic, mostly continuous with clear phrase breaks"},
    {"id": "thrash", "label": "Thrash", "bpm": 180, "key": "E minor", "scale": "phrygian",
     "tags": "thrash metal, fast aggressive palm-muted riffs, rapid double-bass drumming, shredding lead solos, gritty aggressive male vocals, intense, dark",
     "riff": "fast, aggressive palm-muted 16th gallops on the low root with chromatic b2 and tritone (b5) accents; tight, relentless, downpicked",
     "solo": "fast, aggressive phrygian runs hammering the b2 and tritone (b5); relentless 16ths with very few rests, dark and angular, mid-high register", "lead": False},
    {"id": "melodeath", "label": "Melodeath", "bpm": 170, "key": "E minor", "scale": "minor",
     "tags": "melodic death metal, harmonized twin guitar leads, fast double-bass drums, growled vocals, melodic aggressive riffs, driving",
     "riff": "fast melodic tremolo + palm-muted riffing with harmonised lines climbing the minor scale; driving and aggressive",
     "solo": "fast emotive melodic runs climbing the minor scale around a repeated harmonised-sounding motif; driving, mostly continuous with brief phrase breaks"},
    {"id": "death_groove", "label": "Death / groove", "bpm": 140, "key": "E minor", "scale": "phrygian",
     "tags": "death metal, low downtuned palm-muted guitars, syncopated groove riffs, blast and double-bass drums, guttural growled vocals, brutal, heavy",
     "riff": "low, syncopated palm-muted chugs with off-beat rests and occasional b2/b5 pinch-accents; heavy and rhythmic, not busy",
     "solo": "short atonal/chromatic bursts around the b2 and b5 separated by rests; rhythmic and dissonant rather than fast; mid register, not busy"},
    {"id": "black", "label": "Black", "bpm": 180, "key": "F# minor", "scale": "harmonic_minor",
     "tags": "black metal, fast tremolo-picked guitars, relentless blast beats, shrieking raspy vocals, cold raw atmosphere, icy, lo-fi, dark",
     "riff": "fast, cold tremolo-picked single notes climbing the scale (steady 16ths, few rests), bleak and melodic", "lead": True, "reg": 12,
     "solo": "cold relentless tremolo melody — steady high 16th single notes weaving up and down harmonic minor with almost no rests; bleak, hypnotic, atmospheric"},
    {"id": "doom", "label": "Doom", "bpm": 80, "key": "C minor", "scale": "minor",
     "tags": "doom metal, slow heavy downtuned distorted guitars, crushing drums, mournful clean vocals, thick, dark, atmospheric, heavy",
     "riff": "very slow and heavy; sparse SUSTAINED power chords with lots of empty space (many rests), crushing and deliberate",
     "solo": "slow, mournful and spacious — a few sustained high notes with long rests between them; bluesy minor phrasing, lots of empty space, never busy"},
    {"id": "progressive", "label": "Progressive", "bpm": 140, "key": "C# minor", "scale": "dorian",
     "tags": "progressive metal, intricate technical riffs, shifting time signatures, atmospheric keyboards, dynamic builds, powerful clean vocals, expansive",
     "riff": "intricate, technical, syncopated riffing with odd accents and melodic moves; modal and dynamic",
     "solo": "technical and expressive — fast legato runs and wide interval leaps woven around a recurring melodic motif; shifting density with deliberate rests; ranges wide"},
    {"id": "gothic", "label": "Gothic", "bpm": 110, "key": "D minor", "scale": "minor",
     "tags": "gothic metal, melancholic brooding atmosphere, lush keyboards, downtuned guitars, deep clean vocals, female operatic vocals, dark romantic",
     "riff": "slow-to-mid, brooding power chords under lush keys; melancholic and spacious",
     "solo": "melancholic singing lead — slow expressive phrases of held notes and gentle runs with space between; dark and romantic, mid register"},
    {"id": "groove", "label": "Groove", "bpm": 125, "key": "C minor", "scale": "phrygian",
     "tags": "groove metal, heavy syncopated mid-tempo riffs, punchy downtuned guitars, pounding drums, aggressive shouted vocals, bouncy, powerful",
     "riff": "heavy syncopated mid-tempo chugs with bouncy groove and rests; punchy and rhythmic",
     "solo": "bluesy aggressive lead — punchy mid-tempo phrases around the low scale with groovy rests and a repeated lick; swaggering, not too busy"},
    {"id": "djent", "label": "Djent", "bpm": 120, "key": "F# minor", "scale": "phrygian",
     "tags": "djent, polyrhythmic palm-muted riffs, extended-range guitars, tight syncopated grooves, ambient clean sections, percussive, modern production",
     "riff": "tight low palm-muted polyrhythmic chugs with syncopated rests and the occasional high accent; percussive and modern",
     "solo": "ambient melodic lead floating over the groove — legato runs and wide melodic leaps with breathing space between phrases; modern, mid-high register"},
    {"id": "industrial", "label": "Industrial", "bpm": 130, "key": "E minor", "scale": "phrygian",
     "tags": "industrial metal, mechanical rhythms, distorted guitars, electronic beats, cold synth textures, harsh vocals, aggressive, machine-like",
     "riff": "mechanical, repetitive palm-muted chugs locked to a machine-like grid; cold and aggressive",
     "solo": "cold and repetitive — a short robotic motif repeated with dissonant accents, locked rigidly to the grid; sparse and mechanical"},
    {"id": "viking", "label": "Viking", "bpm": 150, "key": "E minor", "scale": "minor",
     "tags": "viking metal, epic folk melodies, choir chants, distorted guitars, double-bass drums, anthemic gang vocals, orchestral, heroic, battle atmosphere",
     "riff": "epic, anthemic mid-fast power chords with folk-melodic moves; heroic and chant-like",
     "solo": "epic anthemic lead — big folk-melodic runs and a chant-like repeated motif climbing to sustained high notes; heroic, moderate density"},
    {"id": "pirate", "label": "Pirate", "bpm": 175, "key": "E minor", "scale": "minor",
     "tags": "pirate metal, fast galloping power metal riffs, accordion and keytar leads, jaunty folk melodies, double-bass drums, gruff rowdy gang vocals, sea shanty energy, festive, anthemic, swashbuckling",
     "riff": "fast galloping power-metal riff with jaunty sea-shanty folk melodies; festive and rowdy",
     "solo": "jaunty fast folk-melodic lead — bouncy sea-shanty runs and a catchy repeated motif; festive and swashbuckling, mostly continuous with playful rests"},
    {"id": "hard_rock", "label": "Hard rock", "bpm": 120, "key": "A minor", "scale": "pentatonic_minor",
     "tags": "hard rock, crunchy overdriven guitars, driving backbeat drums, punchy bass, powerful rock vocals, energetic, anthemic",
     "riff": "mid-tempo driving power chords with swagger and space; pentatonic, punchy, not too busy",
     "solo": "tasteful pentatonic rock lead — bluesy medium-fast phrases and a repeated lick with plenty of space; swaggering, mid register, leave rests"},
    {"id": "accdc", "label": "AC/DC", "parent": "hard_rock", "bpm": 120, "key": "A major", "scale": "pentatonic_minor",
     "tags": "hard rock, AC/DC style, crunchy overdriven Marshall guitars, swinging backbeat, gang-shout backing vocals, raspy male vocal, mid tempo, live-room production",
     "riff": "mid-tempo big OPEN power chords with space and swing between hits; simple, pentatonic, swaggering — leave rests for groove",
     "solo": "simple swaggering pentatonic blues-rock licks — short punchy phrases with big rests and a repeated hook; attitude over speed, mid register"},
    {"id": "southern", "label": "Southern rock", "bpm": 110, "key": "A minor", "scale": "blues",
     "tags": "southern hard rock, bluesy thick overdriven guitar riffs, groovy drums, soulful gritty male vocal, mid tempo, Black Stone Cherry style",
     "riff": "bluesy, groovy pentatonic riffing with b5 passing notes; thick, mid-tempo, soulful",
     "solo": "soulful bluesy lead with b5 passing notes — expressive medium-paced pentatonic phrases and repeated licks with breathing space; groovy and gritty"},
    {"id": "arena", "label": "Arena rock", "bpm": 130, "key": "G major", "scale": "major",
     "tags": "80s arena rock, anthemic, big layered guitars, huge hooky chorus, polished production, gated-reverb drums, soaring male vocal, Bon Jovi style",
     "riff": "anthemic, simple and major-key; big ringing power chords, mid-tempo, hooky and uplifting",
     "solo": "melodic singable major-key lead — anthemic medium runs resolving onto held high notes; hooky and uplifting with balanced rests"},
]

BY_ID = {g["id"]: g for g in GENRES}
