"""Unified genre registry — the SINGLE source of truth for genre/style info,
used everywhere it's needed:

- `tags`  → ACE-Step generation tag bundle (the Generate/Song/Restyle preset chips)
- `bpm` / `key` → SUGGESTED tempo + key (suggestions, never force-applied)
- `scale` → modal scale the symbolic riff/solo generator realises against
- `riff`  → LLM prompt feel for a rhythm riff
- `solo`  → LLM prompt feel for a lead solo
- `lead`  → riff renders single notes (shred) instead of power chords (optional)
- `reg`   → register offset in semitones for the riff/solo (optional)

Exposed to the frontend via /api/config ("genres") and consumed by guitar.py
for symbolic riff/solo generation. Add a genre here once → it appears in the
generation chips AND the Guitar riff/solo genre pickers.
"""

GENRES = [
    {"id": "power", "label": "Power", "bpm": 175, "key": "E minor", "scale": "minor",
     "tags": "power metal, galloping double-bass drums, fast palm-muted distorted guitars, twin lead guitar harmonies, soaring clean operatic male vocals, orchestral keyboards, triumphant, epic, fast tempo",
     "riff": "fast galloping, melodic and uplifting; mostly root chugs with soaring runs up to 5/8 and harmonised-sounding leaps",
     "solo": "fast melodic legato runs and harmonised leads with triumphant, singable phrasing"},
    {"id": "neoclassical", "label": "Neoclassical", "bpm": 168, "key": "A minor", "scale": "harmonic_minor",
     "lead": True, "reg": 24,
     "tags": "neoclassical metal, virtuoso shred lead guitar, fast sweep-picked arpeggios and harmonic-minor scalar runs, baroque classical influence, galloping double-bass drums, harpsichord and orchestral keyboards, soaring operatic male vocals, dramatic, Yngwie Malmsteen style",
     "riff": "virtuosic neoclassical shred (Yngwie/Becker): FAST continuous 16th SINGLE-NOTE harmonic-minor runs (raised-7th leading tone), pedal-point lines and diminished/sequence flurries; busy, few rests, ranging high (degrees to 12-15); a lead line, NOT power chords",
     "solo": "full shred solo: sweep-picked arpeggios, harmonic-minor scalar runs, pedal-point and diminished flurries, baroque sequences — fast, dramatic, virtuosic"},
    {"id": "symphonic", "label": "Symphonic", "bpm": 150, "key": "D minor", "scale": "minor",
     "tags": "symphonic metal, lush orchestral strings, epic choir, heavily distorted guitars, double-bass drums, soaring operatic female vocals, cinematic, dramatic, grand",
     "riff": "grand, mid-fast power chords supporting an orchestra; melodic, dramatic, with melodic moves up the minor scale",
     "solo": "melodic, cinematic lead following the orchestra; expressive runs and sustained singing notes"},
    {"id": "folk_metal", "label": "Folk", "bpm": 160, "key": "E minor", "scale": "dorian",
     "tags": "folk metal, distorted electric guitars, double-bass drums, folk melody, violin, flute, accordion, anthemic gang vocals, festive, energetic",
     "riff": "lively, modal and melodic (dorian); bouncy mid-fast riff with folky melodic runs, major-ish",
     "solo": "lively folk-dance melodic lead, modal runs and ornaments, jaunty"},
    {"id": "heavy", "label": "Heavy", "bpm": 140, "key": "E minor", "scale": "minor",
     "tags": "heavy metal, crunchy distorted electric guitars, twin guitar harmonies, driving drums, powerful melodic male vocals, classic, high energy",
     "riff": "classic mid-tempo heavy-metal riffing; crunchy power chords with melodic moves and the occasional gallop",
     "solo": "classic melodic metal lead with bends, vibrato and fast runs"},
    {"id": "nwobhm", "label": "NWOBHM", "bpm": 160, "key": "E minor", "scale": "minor",
     "tags": "NWOBHM, galloping twin-guitar harmonies, melodic distorted guitars, driving drums, soaring melodic male vocals, Iron Maiden style, heroic, energetic",
     "riff": "galloping, melodic and harmonised (Maiden-style); running 8th+16th gallops with melodic moves up the scale, heroic",
     "solo": "melodic harmonised twin-lead phrasing with bends and fast runs, heroic"},
    {"id": "thrash", "label": "Thrash", "bpm": 180, "key": "E minor", "scale": "phrygian",
     "tags": "thrash metal, fast aggressive palm-muted riffs, rapid double-bass drumming, shredding lead solos, gritty aggressive male vocals, intense, dark",
     "riff": "fast, aggressive palm-muted 16th gallops on the low root with chromatic b2 and tritone (b5) accents; tight, relentless, downpicked",
     "solo": "fast chromatic alternate-picked runs and aggressive tremolo, dark phrygian licks", "lead": False},
    {"id": "melodeath", "label": "Melodeath", "bpm": 170, "key": "E minor", "scale": "minor",
     "tags": "melodic death metal, harmonized twin guitar leads, fast double-bass drums, growled vocals, melodic aggressive riffs, driving",
     "riff": "fast melodic tremolo + palm-muted riffing with harmonised lines climbing the minor scale; driving and aggressive",
     "solo": "harmonised melodic lead with fast tremolo runs and emotive bends"},
    {"id": "death_groove", "label": "Death / groove", "bpm": 140, "key": "E minor", "scale": "phrygian",
     "tags": "death metal, low downtuned palm-muted guitars, syncopated groove riffs, blast and double-bass drums, guttural growled vocals, brutal, heavy",
     "riff": "low, syncopated palm-muted chugs with off-beat rests and occasional b2/b5 pinch-accents; heavy and rhythmic, not busy",
     "solo": "atonal/chromatic bursts, pinch harmonics, dissonant and rhythmic"},
    {"id": "black", "label": "Black", "bpm": 180, "key": "F# minor", "scale": "harmonic_minor",
     "tags": "black metal, fast tremolo-picked guitars, relentless blast beats, shrieking raspy vocals, cold raw atmosphere, icy, lo-fi, dark",
     "riff": "fast, cold tremolo-picked single notes climbing the scale (steady 16ths, few rests), bleak and melodic", "lead": True, "reg": 12,
     "solo": "cold tremolo-picked melodic runs in harmonic minor, bleak and atmospheric"},
    {"id": "doom", "label": "Doom", "bpm": 80, "key": "C minor", "scale": "minor",
     "tags": "doom metal, slow heavy downtuned distorted guitars, crushing drums, mournful clean vocals, thick, dark, atmospheric, heavy",
     "riff": "very slow and heavy; sparse SUSTAINED power chords with lots of empty space (many rests), crushing and deliberate",
     "solo": "slow, mournful bluesy bends and sustained wailing notes with space"},
    {"id": "progressive", "label": "Progressive", "bpm": 140, "key": "C# minor", "scale": "dorian",
     "tags": "progressive metal, intricate technical riffs, shifting time signatures, atmospheric keyboards, dynamic builds, powerful clean vocals, expansive",
     "riff": "intricate, technical, syncopated riffing with odd accents and melodic moves; modal and dynamic",
     "solo": "technical, expressive lead mixing legato runs, wide intervals and melodic motifs"},
    {"id": "gothic", "label": "Gothic", "bpm": 110, "key": "D minor", "scale": "minor",
     "tags": "gothic metal, melancholic brooding atmosphere, lush keyboards, downtuned guitars, deep clean vocals, female operatic vocals, dark romantic",
     "riff": "slow-to-mid, brooding power chords under lush keys; melancholic and spacious",
     "solo": "melancholic, singing lead with slow bends and vibrato, dark and romantic"},
    {"id": "groove", "label": "Groove", "bpm": 125, "key": "C minor", "scale": "phrygian",
     "tags": "groove metal, heavy syncopated mid-tempo riffs, punchy downtuned guitars, pounding drums, aggressive shouted vocals, bouncy, powerful",
     "riff": "heavy syncopated mid-tempo chugs with bouncy groove and rests; punchy and rhythmic",
     "solo": "bluesy aggressive lead with pinch harmonics, bends and wah-style phrasing"},
    {"id": "djent", "label": "Djent", "bpm": 120, "key": "F# minor", "scale": "phrygian",
     "tags": "djent, polyrhythmic palm-muted riffs, extended-range guitars, tight syncopated grooves, ambient clean sections, percussive, modern production",
     "riff": "tight low palm-muted polyrhythmic chugs with syncopated rests and the occasional high accent; percussive and modern",
     "solo": "ambient, melodic lead with wide bends and legato over the groove"},
    {"id": "industrial", "label": "Industrial", "bpm": 130, "key": "E minor", "scale": "phrygian",
     "tags": "industrial metal, mechanical rhythms, distorted guitars, electronic beats, cold synth textures, harsh vocals, aggressive, machine-like",
     "riff": "mechanical, repetitive palm-muted chugs locked to a machine-like grid; cold and aggressive",
     "solo": "cold, processed lead with robotic repetition and dissonant accents"},
    {"id": "viking", "label": "Viking", "bpm": 150, "key": "E minor", "scale": "minor",
     "tags": "viking metal, epic folk melodies, choir chants, distorted guitars, double-bass drums, anthemic gang vocals, orchestral, heroic, battle atmosphere",
     "riff": "epic, anthemic mid-fast power chords with folk-melodic moves; heroic and chant-like",
     "solo": "epic anthemic lead with folk-melodic runs and big sustained notes"},
    {"id": "pirate", "label": "Pirate", "bpm": 175, "key": "E minor", "scale": "minor",
     "tags": "pirate metal, fast galloping power metal riffs, accordion and keytar leads, jaunty folk melodies, double-bass drums, gruff rowdy gang vocals, sea shanty energy, festive, anthemic, swashbuckling",
     "riff": "fast galloping power-metal riff with jaunty sea-shanty folk melodies; festive and rowdy",
     "solo": "jaunty fast folk-melodic lead, festive and swashbuckling"},
    {"id": "hard_rock", "label": "Hard rock", "bpm": 120, "key": "A minor", "scale": "pentatonic_minor",
     "tags": "hard rock, crunchy overdriven guitars, driving backbeat drums, punchy bass, powerful rock vocals, energetic, anthemic",
     "riff": "mid-tempo driving power chords with swagger and space; pentatonic, punchy, not too busy",
     "solo": "pentatonic bends, vibrato and bluesy rock phrasing, tasteful"},
    {"id": "accdc", "label": "AC/DC crunch", "bpm": 120, "key": "A major", "scale": "pentatonic_minor",
     "tags": "hard rock, AC/DC style, crunchy overdriven Marshall guitars, swinging backbeat, gang-shout backing vocals, raspy male vocal, mid tempo, live-room production",
     "riff": "mid-tempo big OPEN power chords with space and swing between hits; simple, pentatonic, swaggering — leave rests for groove",
     "solo": "simple pentatonic blues-rock licks with attitude and big bends"},
    {"id": "southern", "label": "Southern rock", "bpm": 110, "key": "A minor", "scale": "blues",
     "tags": "southern hard rock, bluesy thick overdriven guitar riffs, groovy drums, soulful gritty male vocal, mid tempo, Black Stone Cherry style",
     "riff": "bluesy, groovy pentatonic riffing with b5 passing notes; thick, mid-tempo, soulful",
     "solo": "bluesy pentatonic with b5, expressive bends and slides, soulful"},
    {"id": "arena", "label": "Arena rock", "bpm": 130, "key": "G major", "scale": "major",
     "tags": "80s arena rock, anthemic, big layered guitars, huge hooky chorus, polished production, gated-reverb drums, soaring male vocal, Bon Jovi style",
     "riff": "anthemic, simple and major-key; big ringing power chords, mid-tempo, hooky and uplifting",
     "solo": "melodic, singable major-key lead with big bends, anthemic"},
]

BY_ID = {g["id"]: g for g in GENRES}
